services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - apartment-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - apartment-network

networks:
  apartment-network:
    driver: bridge